(function(){'use strict';const root=document.createElement('div');root.className='cloud-bar';const open=document.createElement('button');open.type='button';open.id='cloud-open';open.textContent='正在连接云端…';root.append(open);document.querySelector('header').after(root);
const panel=document.createElement('dialog');panel.id='cloud-dialog';panel.innerHTML=`<button type="button" id="cloud-close" aria-label="关闭云端记录">×</button><p class="cloud-kicker">YOUR MOMENTS, KEPT</p><h2>让这一刻留下来。</h2><p id="cloud-message" role="status"></p><button id="cloud-restore" type="button">重新恢复登录</button><p id="cloud-origin"></p><p id="cloud-feedback" role="status"></p><form id="cloud-login"><label for="cloud-email">你的邮箱</label><input id="cloud-email" type="email" autocomplete="email" required placeholder="you@example.com"><label for="cloud-password">网站密码</label><input id="cloud-password" type="password" autocomplete="current-password" placeholder="不是 Supabase 控制台密码"><button type="submit" id="cloud-password-login">使用密码登录</button><button type="button" id="cloud-send-link">改用邮件链接登录</button><p>首次使用仍需通过邮件登录；登录后可设置网站密码，以后不用反复收邮件。密码登录仍受正常的登录尝试限制。</p></form><section id="cloud-account" hidden><p id="cloud-email-label"></p><div class="cloud-actions"><button id="cloud-refresh">刷新云端记录</button><button id="cloud-retry">重试待同步记录</button><button id="cloud-migrate">上传本浏览器旧记录</button><button id="cloud-export">导出备份</button></div><p id="cloud-old-count"></p><div id="cloud-list"></div><details><summary>设置网站登录密码</summary><form id="cloud-set-password"><label for="cloud-new-password">新密码（至少 10 个字符）</label><input id="cloud-new-password" type="password" autocomplete="new-password" minlength="10" required><label for="cloud-confirm-password">再输入一次</label><input id="cloud-confirm-password" type="password" autocomplete="new-password" minlength="10" required><button id="cloud-save-password" type="submit">保存网站密码</button><p>密码直接提交给 Supabase，不写入项目文件或浏览器记录。</p></form></details><button id="cloud-logout">退出当前设备</button></section><button id="cloud-local-export">导出本地旧记录备份</button>`;document.body.append(panel);
const $=s=>panel.querySelector(s);function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function draw(){const s=AtlasRecords.state();open.textContent=s.phase==='restoring'?'正在恢复登录…':s.user?(s.phase==='error'?'云端连接需检查':s.pending?'有 '+s.pending+' 条待同步':'云端记录 · '+s.count):'登录并保存到云端';$('#cloud-message').textContent=s.message;$('#cloud-origin').textContent='当前网站：'+s.origin+'。登录状态按浏览器和网址分别保存。';$('#cloud-restore').hidden=!!s.user&&s.phase!=='error';$('#cloud-login').hidden=!!s.user||s.phase==='restoring';$('#cloud-account').hidden=!s.user;$('#cloud-email-label').textContent=s.user?.email||'';$('#cloud-retry').hidden=!s.pending;let old=[];try{old=AtlasRecords.legacy()}catch{}$('#cloud-migrate').hidden=!old.length;$('#cloud-old-count').textContent=old.length?'本浏览器保留 '+old.length+' 条旧记录，只有点击上传才会迁移；上传后仍保留本地原件。':'';$('#cloud-local-export').hidden=!old.length;const list=$('#cloud-list');list.replaceChildren();AtlasRecords.read().slice().sort((a,b)=>new Date(b.recordedAt)-new Date(a.recordedAt)).slice(0,30).forEach(r=>{const a=document.createElement('a');const path=location.pathname.includes('/tutu/')?'map.html':'tutu/map.html';a.href=path+'#record='+encodeURIComponent(r.id);a.textContent=r.title;const date=document.createElement('small');date.textContent=new Date(r.recordedAt).toLocaleString('zh-CN');a.append(date);a.onclick=()=>panel.close();list.append(a)})}
async function act(button,fn){button.disabled=true;$('#cloud-feedback').textContent='';try{await fn()}catch(e){$('#cloud-feedback').textContent=/频繁|额度|rate.limit|too many/i.test(e.message)?'暂时无法登录，请稍后重试。':e.message}finally{button.disabled=false;draw()}}
open.onclick=()=>{draw();panel.showModal()};$('#cloud-close').onclick=()=>panel.close();$('#cloud-login').onsubmit=e=>{e.preventDefault();if(!$('#cloud-password').value){$('#cloud-feedback').textContent='请填写已设置的网站密码，或选择邮件链接登录。';return}act($('#cloud-password-login'),async()=>{try{await AtlasRecords.signInPassword($('#cloud-email').value,$('#cloud-password').value);$('#cloud-feedback').textContent='登录成功。'}finally{$('#cloud-password').value=''}})};
$('#cloud-send-link').onclick=()=>{if(!$('#cloud-email').reportValidity())return;act($('#cloud-send-link'),async()=>{await AtlasRecords.signIn($('#cloud-email').value);$('#cloud-feedback').textContent='登录邮件已发送，请检查邮箱。登录后可以设置网站密码。'})};
$('#cloud-set-password').onsubmit=e=>{e.preventDefault();if($('#cloud-new-password').value!==$('#cloud-confirm-password').value){$('#cloud-feedback').textContent='两次密码不一致。';return}act($('#cloud-save-password'),async()=>{try{await AtlasRecords.setPassword($('#cloud-new-password').value);$('#cloud-feedback').textContent='网站密码已设置。以后可直接用邮箱和这个密码登录。'}finally{$('#cloud-new-password').value='';$('#cloud-confirm-password').value=''}})};
$('#cloud-restore').onclick=()=>act($('#cloud-restore'),async()=>{await AtlasRecords.restore();await AtlasRecords.refresh()});$('#cloud-refresh').onclick=()=>act($('#cloud-refresh'),()=>AtlasRecords.refresh());$('#cloud-retry').onclick=()=>act($('#cloud-retry'),()=>AtlasRecords.retry());$('#cloud-migrate').onclick=()=>act($('#cloud-migrate'),()=>AtlasRecords.migrate());$('#cloud-logout').onclick=()=>act($('#cloud-logout'),()=>AtlasRecords.signOut());$('#cloud-export').onclick=()=>download({exportedAt:new Date().toISOString(),records:AtlasRecords.read(),pending:AtlasRecords.pending()},'my-moments-backup.json');$('#cloud-local-export').onclick=()=>{try{download({records:AtlasRecords.legacy()},'local-moments-backup.json')}catch(e){$('#cloud-feedback').textContent=e.message}};
window.addEventListener('atlas-cloud-state',draw);window.AtlasCloudUI={open:()=>{draw();panel.showModal()}};draw();
})();
