(function(){'use strict';
const legacyKey='between-surfaces.records.v1',config=window.ATLAS_CLOUD_CONFIG;
const client=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let user=null,records=[],phase='loading',message='',revision=0,busySync=false,started=false;
function readList(key){const text=localStorage.getItem(key);if(!text)return[];const data=JSON.parse(text);if(!Array.isArray(data))throw Error('本地记录格式无法读取，请先导出备份。');return data.filter(r=>r&&typeof r.id==='string'&&typeof r.text==='string'&&typeof r.title==='string')}
function cacheKey(id){return 'between-surfaces.cloud-cache.v1.'+id}function queueKey(id){return 'between-surfaces.cloud-pending.v1.'+id}
function pending(){if(!user)return[];return readList(queueKey(user.id))}
function legacy(){return readList(legacyKey)}
function notify(){window.dispatchEvent(new Event('atlas-records-changed'));window.dispatchEvent(new Event('atlas-cloud-state'))}
function state(){let count=0;try{count=pending().length}catch{}return {user:user?{id:user.id,email:user.email}:null,phase,message,count:records.length,pending:count}}
function errorText(error){const text=error?.message||String(error);if(/atlas_moments|PGRST205|42P01/.test(text))return '数据库尚未就绪，请先在 Supabase 运行建表脚本。';if(/permission denied|row-level|42501/.test(text))return '数据库权限尚未配置完成，请重新运行建表脚本。';if(/fetch|network|Load failed/i.test(text))return '网络连接失败。文字仍在本地，请联网后重试。';if(/rate limit/i.test(text))return '操作过于频繁，请稍后再试。';if(/email.*not.*allowed|not authorized/i.test(text))return '该邮箱暂时不能接收登录邮件，请检查 Supabase 的邮箱发送设置。';return text}
function cache(){if(user)try{localStorage.setItem(cacheKey(user.id),JSON.stringify(records))}catch{message='云端记录已加载，但浏览器无法缓存；请保持联网。'}}
function validate(r){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(r.id))throw Error('记录编号无效。');if(!r.title?.trim()||!r.text?.trim()||r.title.length>160||r.text.length>10000)throw Error('请检查标题和文字长度。');if(!Number.isFinite(new Date(r.recordedAt).getTime()))throw Error('记录时间无效。');return {id:r.id,title:r.title,text:r.text,recordedAt:r.recordedAt,place:r.place||'',object:r.object||'',body:r.body||'',mood:r.mood||'',senses:Array.isArray(r.senses)?r.senses:[],color:/^#[a-f0-9]{6}$/i.test(r.color)?r.color:'#94b9ad'}}
async function add(input){await ready;if(!user)throw Error('请先登录，再将这一刻保存到云端。');const r=validate(input),uid=user.id;const queued=readList(queueKey(uid));const index=queued.findIndex(x=>x.id===r.id);if(index>=0)queued[index]=r;else queued.push(r);localStorage.setItem(queueKey(uid),JSON.stringify(queued));revision++;phase='saving';message='正在保存到云端…';notify();
try{const {data,error}=await client.from('atlas_moments').upsert({id:r.id,user_id:uid,payload:r},{onConflict:'id'}).select('id,payload,user_id').single();if(error)throw error;if(!data||data.id!==r.id||data.user_id!==uid)throw Error('尚未得到数据库的保存确认，请重试。');const left=readList(queueKey(uid)).filter(x=>x.id!==r.id);localStorage.setItem(queueKey(uid),JSON.stringify(left));if(user?.id===uid){records=records.filter(x=>x.id!==r.id);records.push({...data.payload,id:data.id});revision++;cache();phase='ready';message='已保存到云端';notify()}return r;
}catch(error){if(user?.id===uid){phase='error';message=errorText(error)+' 本条仍待同步。';notify()}throw Error(errorText(error))}}
async function refresh(){await ready;if(!user)return;const uid=user.id,version=revision;phase='loading';message='正在读取云端记录…';window.dispatchEvent(new Event('atlas-cloud-state'));try{const list=[];for(let offset=0;;offset+=500){const {data,error}=await client.from('atlas_moments').select('id,payload').eq('user_id',uid).order('created_at',{ascending:true}).order('id',{ascending:true}).range(offset,offset+499);if(error)throw error;list.push(...data.map(row=>({...row.payload,id:row.id})));if(data.length<500)break}if(user?.id!==uid||revision!==version)return;records=list;cache();phase='ready';message='已从云端加载 '+records.length+' 条记录';notify()}catch(error){if(user?.id===uid){phase='error';message=errorText(error)+(records.length?' 当前显示上次缓存。':'');notify()}}}
async function retry(){await ready;if(!user)throw Error('请先登录。');if(busySync)return;busySync=true;try{for(const r of pending())await add(r);await refresh()}finally{busySync=false}}
async function migrate(){await ready;if(!user)throw Error('请先登录。');if(busySync)return;busySync=true;try{for(const r of legacy())await add(r);await refresh()}finally{busySync=false}}
function acceptSession(session){const next=session?.user||null;if(started&&next?.id===user?.id)return;revision++;user=next;records=[];if(user){try{records=readList(cacheKey(user.id))}catch{}phase='loading';message='正在读取云端记录…'}else{phase='signedout';message='登录，让记录保存在云端'}notify();if(started&&user)setTimeout(()=>refresh(),0)}
const ready=(async()=>{const {data,error}=await client.auth.getSession();if(error){phase='error';message=errorText(error)}acceptSession(data?.session);started=true;return true})();
client.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>acceptSession(session),0)});
async function signIn(email){const redirect=new URL(location.pathname.includes('/tutu/')?'../mobile.html':'mobile.html',location.href);redirect.hash='';redirect.search='';const {error}=await client.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:redirect.href,shouldCreateUser:true}});if(error)throw Error(errorText(error))}
async function signOut(){const {error}=await client.auth.signOut({scope:'local'});if(error)throw Error(errorText(error));acceptSession(null)}
window.AtlasRecords={key:legacyKey,read:()=>records.slice(),add,refresh,retry,migrate,legacy,pending,state,ready,signIn,signOut};
ready.then(()=>{notify();if(user)refresh()});window.addEventListener('online',()=>{if(user)retry().catch(()=>{})});window.addEventListener('focus',()=>{if(user&&!busySync)refresh()});
})();

