(function(){'use strict';
const legacyKey='between-surfaces.records.v1',config=window.ATLAS_CLOUD_CONFIG;
const authStorageKey='sb-'+new URL(config.url).hostname.split('.')[0]+'-auth-token';
let storageFailure='';
const authStorage={getItem(key){try{return localStorage.getItem(key)}catch{storageFailure='Your browser blocked sign-in storage. Allow site storage, then try again.';throw Error(storageFailure)}},setItem(key,value){try{localStorage.setItem(key,value);if(localStorage.getItem(key)!==value)throw Error('Storage verification failed')}catch{storageFailure='Your browser did not keep the sign-in. Allow site storage or use a regular browsing window so refresh can keep you signed in.';throw Error(storageFailure)}},removeItem(key){try{localStorage.removeItem(key)}catch{storageFailure='The saved sign-in could not be cleared from this device.';throw Error(storageFailure)}}};
const client=window.supabase.createClient(config.url,config.publishableKey,{auth:{storage:authStorage,storageKey:authStorageKey,persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let user=null,records=[],phase='restoring',message='Restoring sign-in…',revision=0,busySync=false,started=false;
function readList(key){const text=localStorage.getItem(key);if(!text)return[];const data=JSON.parse(text);if(!Array.isArray(data))throw Error('The local moments could not be read. Export a backup first.');return data.filter(r=>r&&typeof r.id==='string'&&typeof r.text==='string'&&typeof r.title==='string')}
function cacheKey(id){return 'between-surfaces.cloud-cache.v1.'+id}function queueKey(id){return 'between-surfaces.cloud-pending.v1.'+id}
function pending(){if(!user)return[];return readList(queueKey(user.id))}
function legacy(){return readList(legacyKey)}
function notify(){window.dispatchEvent(new Event('atlas-records-changed'));window.dispatchEvent(new Event('atlas-cloud-state'))}
function state(){let count=0;try{count=pending().length}catch{}return {storageFailure,origin:location.origin,user:user?{id:user.id,email:user.email}:null,phase,message,count:records.length,pending:count}}
function errorText(error){const text=error?.message||String(error);if(/atlas_moments|PGRST205|42P01/.test(text))return 'The database is not ready yet. Run the setup script in Supabase first.';if(/permission denied|row-level|42501/.test(text))return 'Database permissions are incomplete. Run the setup script again.';if(/fetch|network|Load failed/i.test(text))return 'The network connection failed. Your words are still here; try again when you are online.';if(error?.code==='over_email_send_rate_limit'||/email rate limit/i.test(text))return 'Supabase has reached its email limit. This is not a limit from the site; try the email later, or use a site password you already set.';if(error?.code==='over_request_rate_limit'||/rate limit|security purposes|after.*seconds/i.test(text))return 'Supabase is temporarily limiting repeated requests. Wait a little, or use your site password if you already set one.';if(/invalid login credentials/i.test(text))return 'The email or site password is incorrect. This is not your Supabase dashboard password; set a site password after signing in by email.';if(/email.*not.*allowed|not authorized/i.test(text))return 'This address cannot receive a sign-in email right now. Check the email settings in Supabase.';return text}
function cache(){if(user)try{localStorage.setItem(cacheKey(user.id),JSON.stringify(records))}catch{message='Cloud moments are loaded, but this browser cannot cache them. Stay online.'}}
function validate(r){if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(r.id))throw Error('This moment has an invalid ID.');if(!r.title?.trim()||!r.text?.trim()||r.title.length>160||r.text.length>10000)throw Error('Check the length of the title and text.');if(!Number.isFinite(new Date(r.recordedAt).getTime()))throw Error('The date or time is invalid.');return {id:r.id,title:r.title,text:r.text,recordedAt:r.recordedAt,place:r.place||'',object:r.object||'',body:r.body||'',mood:r.mood||'',senses:Array.isArray(r.senses)?r.senses:[],color:/^#[a-f0-9]{6}$/i.test(r.color)?r.color:'#94b9ad'}}
async function add(input){await ready;if(!user)throw Error('Sign in before saving this moment to the cloud.');const r=validate(input),uid=user.id;const queued=readList(queueKey(uid));const index=queued.findIndex(x=>x.id===r.id);if(index>=0)queued[index]=r;else queued.push(r);localStorage.setItem(queueKey(uid),JSON.stringify(queued));revision++;phase='saving';message='Saving to the cloud…';notify();
try{const {data,error}=await client.from('atlas_moments').upsert({id:r.id,user_id:uid,payload:r},{onConflict:'id'}).select('id,payload,user_id').single();if(error)throw error;if(!data||data.id!==r.id||data.user_id!==uid)throw Error('The database has not confirmed the save yet. Please try again.');const left=readList(queueKey(uid)).filter(x=>x.id!==r.id);localStorage.setItem(queueKey(uid),JSON.stringify(left));if(user?.id===uid){records=records.filter(x=>x.id!==r.id);records.push({...data.payload,id:data.id});revision++;cache();phase='ready';message='Saved to the cloud';notify()}return r;
}catch(error){if(user?.id===uid){phase='error';message=errorText(error)+' This moment is still waiting to sync.';notify()}throw Error(errorText(error))}}
async function refresh(){await ready;if(!user)return;const uid=user.id,version=revision;phase='loading';message='Loading cloud moments…';window.dispatchEvent(new Event('atlas-cloud-state'));try{const list=[];for(let offset=0;;offset+=500){const {data,error}=await client.from('atlas_moments').select('id,payload').eq('user_id',uid).order('created_at',{ascending:true}).order('id',{ascending:true}).range(offset,offset+499);if(error)throw error;list.push(...data.map(row=>({...row.payload,id:row.id})));if(data.length<500)break}if(user?.id!==uid||revision!==version)return;records=list;cache();phase='ready';message='Loaded '+records.length+' cloud moment(s)';notify()}catch(error){if(user?.id===uid){phase='error';message=errorText(error)+(records.length?' Showing the last cached copy.':'');notify()}}}
async function retry(){await ready;if(!user)throw Error('Sign in first.');if(busySync)return;busySync=true;try{for(const r of pending())await add(r);await refresh()}finally{busySync=false}}
async function migrate(){await ready;if(!user)throw Error('Sign in first.');if(busySync)return;busySync=true;try{for(const r of legacy())await add(r);await refresh()}finally{busySync=false}}
function acceptSession(session){const next=session?.user||null;if(started&&next?.id===user?.id)return;revision++;user=next;records=[];if(user){try{records=readList(cacheKey(user.id))}catch{}phase='loading';message='Loading cloud moments…'}else{phase='signedout';message='Sign in to keep your moments in the cloud'}notify();if(started&&user)setTimeout(()=>refresh(),0)}
let restoring=null;
function restore(){if(restoring)return restoring;restoring=(async()=>{phase='restoring';message='Restoring sign-in…';window.dispatchEvent(new Event('atlas-cloud-state'));try{const {data,error}=await client.auth.getSession();if(error)throw error;const session=data?.session||null;acceptSession(session);if(session?.user){if(storageFailure){phase='error';message=storageFailure}else{phase='ready';message='Sign-in restored'}}else{phase='signedout';message='There is no active sign-in for this browser and site address. Open the email link in this browser.'}started=true;notify();return true}catch(error){phase='error';message=storageFailure||('Sign-in could not be restored: '+errorText(error)+' You can try restoring it again.');started=true;notify();return false}finally{restoring=null}})();return restoring}
const ready=restore();
// Re-read the SDK's current session outside its auth lock. Do not apply a stale
// INITIAL_SESSION snapshot after a newer sign-in/refresh has completed.
client.auth.onAuthStateChange(()=>{setTimeout(async()=>{await ready;const ok=await restore();if(ok&&user)refresh()},0)});
async function signIn(email){const probe='between-surfaces.storage-probe';authStorage.setItem(probe,'ok');authStorage.removeItem(probe);storageFailure='';const redirect=new URL(location.pathname.includes('/tutu/')?'../mobile.html':'mobile.html',location.href);redirect.hash='';redirect.search='';const {error}=await client.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:redirect.href,shouldCreateUser:true}});if(error)throw Error(errorText(error))}
async function signInPassword(email,password){const probe='between-surfaces.storage-probe';authStorage.setItem(probe,'ok');authStorage.removeItem(probe);storageFailure='';const {error}=await client.auth.signInWithPassword({email:email.trim(),password});if(error)throw Error(errorText(error));await restore();await refresh()}
async function setPassword(password){await ready;if(!user)throw Error('Sign in once before setting a site password.');if(password.length<10)throw Error('Use a password with at least 10 characters.');const {error}=await client.auth.updateUser({password});if(error)throw Error(errorText(error))}
async function signOut(){const {error}=await client.auth.signOut({scope:'local'});if(error)throw Error(errorText(error));acceptSession(null)}
window.AtlasRecords={key:legacyKey,read:()=>records.slice(),add,refresh,retry,migrate,legacy,pending,state,ready,restore,signIn,signInPassword,setPassword,signOut};
ready.then(()=>{notify();if(user)refresh()});window.addEventListener('online',async()=>{await restore();if(user)retry().catch(()=>{})});window.addEventListener('focus',()=>{if(user&&!busySync)refresh()});
})();

