/* Local video stays in this browser. No video bytes are sent to the cloud. */
(()=>{'use strict';
const bus=new BroadcastChannel('tutu-background-v1');
function db(){return new Promise((resolve,reject)=>{const req=indexedDB.open('tutu-background-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('media');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function access(mode,action){const store=await db();return new Promise((resolve,reject)=>{const tx=store.transaction('media',mode),r=action(tx.objectStore('media'));tx.oncomplete=()=>{resolve(r.result);store.close()};tx.onerror=()=>{reject(tx.error);store.close()};tx.onabort=()=>{reject(tx.error);store.close()}})}
window.BackgroundStore={read:()=>access('readonly',s=>s.get('current')),async save(file){await access('readwrite',s=>s.put({file,name:file.name||'Local video'},'current'));bus.postMessage({type:'reload'});dispatchEvent(new Event('background-reload'))},settings(){let s={};try{s=JSON.parse(localStorage.getItem('tutu-background-settings')||'{}')}catch{}return {rate:Math.max(1,Math.min(8,Number(s.rate)||4)),blur:Math.max(1,Math.min(24,Number(s.blur)||10)),brightness:Math.max(.1,Math.min(.8,Number(s.brightness)||.35))}},configure(settings){localStorage.setItem('tutu-background-settings',JSON.stringify(settings));bus.postMessage({type:'settings'});dispatchEvent(new Event('background-settings'))},status(text){bus.postMessage({type:'status',text});dispatchEvent(new CustomEvent('background-status',{detail:text}))}};
bus.onmessage=e=>{if(e.data?.type==='reload')dispatchEvent(new Event('background-reload'));if(e.data?.type==='settings')dispatchEvent(new Event('background-settings'));if(e.data?.type==='status')dispatchEvent(new CustomEvent('background-status',{detail:e.data.text}))};
})();

